[package]
name = "h3-util"
version = "0.1.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
indicatif = "0.14"
atty = "0.2"
log = "^0.4"
h3-raster = { path = "../h3-raster" }
