[package]
name = "h3-sys"
version = "0.1.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
build = "build.rs"
license = "MIT"

[build-dependencies]
bindgen = "0.52.0"
cmake = "0.1.42"
regex = "1.3.1"
