[package]
name = "h3ron"
description = "high level rust API including collections for selected parts of H3"
version = "0.5.0"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"
license = "MIT"
keywords = ["geo", "spatial", "h3"]

[dependencies]
h3ron-h3-sys = { path = "../h3ron-h3-sys" }

[dependencies.geo-types]
version = "^0.6"

[dependencies.serde]
version = "^1.0"
features = [ "derive" ]

[dev-dependencies]
bincode = "^1.3"