[package]
name = "h3ron"
version = "0.3.3"
authors = ["Nico Mandery <nico@nmandery.net>"]
edition = "2018"

[dependencies]
h3ron-h3-sys = { path = "../h3ron-h3-sys" }

[dependencies.geo-types]
version = "^0.6"
